### PR TITLE
Avoid XSS Fix #715

### PR DESCRIPTION
**Pull request by alromh87**
Filter is implemented and should be preferred method, that way it protects against code injection in all elements, like divs, img, ...., not just abbr & sup, updating README to make it clearer

### CODE REVIEW

**Review by toufik-airane — COMMENTED** [review]
Dear @alromh87,

I don't understand the issue you're trying to fix.
Thus the contribution doesn't meet our quality requirements. 🚫
Thanks.

**Comment by alromh87** [comment]
It was requested here:
https://github.com/pandao/editor.md/issues/715

and what do you mean by quality requirements?

Are you the same guys who posted the bounty in huntr?

Captura de pantalla de 2020-03-27 14-59-16

**Comment by toufik-airane** [comment]
Dear @alromh87,

My name is Toufik Airane, I'm a security analyst and I've to ensure the quality of deliverable fixes.

The issue here is that you've documented how to fix the issue
but the concept of [huntr.dev](https://huntr.dev) is that **you should concretely fix the issue.**

So feel free to contribute with a concrete patch aiming to mitigate the talked security issue.

**Comment by JamieSlome** [comment]
@alromh87 - can you commit a fix to provide this protection by default and let users opt-out if they want to?

**Comment by alromh87** [comment]
> @alromh87 - can you commit a fix to provide this protection by default and let users opt-out if they want to?

Sure, updated pull request, filters are now enforced, and user has the option to enable scripts and events, this settings are documented in README.md

**Comment by alromh87** [comment]
I tested "examples/html-tags-decode.html" by adding the payloads reported(sup, abbr) as well as div, after the patch alert messages are only shown when AllowOn is set as filterAttr, mitigating the vulnerability by default

**Comment by JamieSlome** [comment]
Thank you for submitting your changes - we will re-review next Friday.

**Comment by JamieSlome** [comment]
@toufik-airane - can we please re-review this?

**Review by toufik-airane — APPROVED** [review]
LGTM

**Review by JamieSlome — APPROVED** [review]
Thanks for your contribution - looks good!

**Comment by huntr-helper** [comment]
Congratulations @alromh87 - your fix has been selected! :tada:<br><br>Thanks for being part of the community & helping secure the world\'s open source code.<br>If you have any questions, please respond in the comments section. Your bounty is on its way - keep hunting!

**Pull request merged**
